if(NOT OPENBLAS_MAKE OR NOT OPENBLAS_BUILD_DIRECTORY OR
	NOT OPENBLAS_COMPILER_DIRECTORY)
	message(FATAL_ERROR "OpenBLAS build parameters are incomplete")
endif()

set(ENV{PATH}
	"${OPENBLAS_COMPILER_DIRECTORY};D:/Git/usr/bin;C:/Windows/System32;C:/Windows")
if(OPENBLAS_IMPORT_LIBRARY_TOOL)
	execute_process(
		COMMAND "${OPENBLAS_MAKE}" -C "${OPENBLAS_BUILD_DIRECTORY}" libs netlib
			OS=WINNT ARCH=x86_64 NO_LAPACKE=1 BUILD_SINGLE=1
			USE_THREAD=0 TARGET=NEHALEM
		COMMAND_ERROR_IS_FATAL ANY
	)
	execute_process(
		COMMAND "${OPENBLAS_MAKE}" -C "${OPENBLAS_BUILD_DIRECTORY}/exports" dll
			OS=WINNT ARCH=x86_64 NO_LAPACKE=1 BUILD_SINGLE=1
			USE_THREAD=0 TARGET=NEHALEM
		COMMAND_ERROR_IS_FATAL ANY
	)
else()
	execute_process(
		COMMAND "${OPENBLAS_MAKE}" -C "${OPENBLAS_BUILD_DIRECTORY}" libs netlib
			OS=WINNT ARCH=x86_64 NO_LAPACKE=1 BUILD_SINGLE=1
			USE_THREAD=0 TARGET=NEHALEM
		COMMAND_ERROR_IS_FATAL ANY
	)
endif()

if(OPENBLAS_IMPORT_LIBRARY_TOOL)
	execute_process(
		COMMAND "${OPENBLAS_IMPORT_LIBRARY_TOOL}" /nologo /machine:x64
			"/def:${OPENBLAS_BUILD_DIRECTORY}/exports/libopenblas.def"
			"/out:${OPENBLAS_BUILD_DIRECTORY}/libopenblas-msvc.lib"
		COMMAND_ERROR_IS_FATAL ANY
	)
else()
	file(COPY_FILE
		"${OPENBLAS_BUILD_DIRECTORY}/libopenblas_nehalem-r0.3.30.a"
		"${OPENBLAS_BUILD_DIRECTORY}/libopenblas.a"
		ONLY_IF_DIFFERENT
	)
endif()