include_guard(GLOBAL)

set(VISION_CAMERA_SDK "NONE" CACHE STRING
	"Camera SDK compiled into VisionRuntime (NONE or HIK_MVS)")
set_property(CACHE VISION_CAMERA_SDK PROPERTY STRINGS NONE HIK_MVS)
set(VISION_INFERENCE_PLATFORM "NONE" CACHE STRING
	"Inference platform compiled into VisionRuntime (NONE, OPENVINO_INTEL, or TENSORRT_NVIDIA)")
set_property(CACHE VISION_INFERENCE_PLATFORM PROPERTY STRINGS
	NONE OPENVINO_INTEL TENSORRT_NVIDIA)
set(VISION_OPENVINO_DEVICE "CPU" CACHE STRING
	"OpenVINO device packaged with the runtime (CPU, GPU, or NPU)")
set_property(CACHE VISION_OPENVINO_DEVICE PROPERTY STRINGS CPU GPU NPU)
set(VISION_MODEL_ARTIFACT_TYPE "ONNX" CACHE STRING
	"Model artifact packaged with the runtime (ONNX, IR, or ENGINE)")
set_property(CACHE VISION_MODEL_ARTIFACT_TYPE PROPERTY STRINGS ONNX IR ENGINE)

if(VISION_INFERENCE_PLATFORM STREQUAL "OPENVINO_INTEL")
	if(NOT VISION_OPENVINO_DEVICE MATCHES "^(CPU|GPU|NPU)$")
		message(FATAL_ERROR
			"VISION_OPENVINO_DEVICE must be CPU, GPU, or NPU")
	endif()
	if(NOT VISION_MODEL_ARTIFACT_TYPE MATCHES "^(ONNX|IR)$")
		message(FATAL_ERROR
			"VISION_MODEL_ARTIFACT_TYPE must be ONNX or IR")
	endif()
elseif(VISION_INFERENCE_PLATFORM STREQUAL "TENSORRT_NVIDIA")
	if(NOT VISION_MODEL_ARTIFACT_TYPE STREQUAL "ENGINE")
		message(FATAL_ERROR
			"TensorRT NVIDIA profile requires VISION_MODEL_ARTIFACT_TYPE=ENGINE")
	endif()
endif()