name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bootstrap dependencies
        run: >-
          cmake
          -DGIT_EXECUTABLE=git
          -DTHIRDPARTY_DIRECTORY="${{ github.workspace }}/Thirdparty"
          -P cmake/bootstrapDependencies.cmake
      - name: Configure
        run: cmake --preset windows-msvc-debug
      - name: Build
        run: cmake --build --preset windows-msvc-debug
      - name: Test
        run: ctest --preset windows-msvc-debug

  linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v5
      - name: Bootstrap dependencies
        run: >-
          cmake
          -DGIT_EXECUTABLE=git
          -DTHIRDPARTY_DIRECTORY="${{ github.workspace }}/Thirdparty"
          -P cmake/bootstrapDependencies.cmake
      - name: Configure
        run: cmake --preset linux-gnu-debug
      - name: Build
        run: cmake --build --preset linux-gnu-debug
      - name: Test
        run: ctest --preset linux-gnu-debug
